In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'Column1': [1, 2, 3, 4, 5],
    'Column2': ['A', 'B', 'C', 'D', 'E'],
    'Column3': [1.1, 2.2, 3.3, 4.4, 5.5]
})
first_three_rows = df.head(3)
print(first_three_rows)

   Column1 Column2  Column3
0        1       A      1.1
1        2       B      2.2
2        3       C      3.3


In [ ]:
import pandas as pd
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'score': [85, 92, 88, 91, 89],
    'age': [20, 25, 22, 23, 24]
}
df = pd.DataFrame(data)
selected_columns = df[['name', 'score']]

print(selected_columns)

      name  score
0    Alice     85
1      Bob     92
2  Charlie     88
3    David     91
4      Eve     89


In [ ]:
import pandas as pd
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'score': [85, 92, 88, 91, 89],
    'attempts': [1, 3, 2, 3, 4]
}
df = pd.DataFrame(data)
attempts_gt_2 = df[df['attempts'] > 2]

print(attempts_gt_2)

    name  score  attempts
1    Bob     92         3
3  David     91         3
4    Eve     89         4


In [ ]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', None],
    'Age': [25, None, 30, 22],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df = pd.DataFrame(data)
column_non_na = df.count()
print("Non-NA values in each column:\n", column_non_na)
row_non_na = df.count(axis=1)
print("\nNon-NA values in each row:\n", row_non_na)

Non-NA values in each column:
 Name    3
Age     3
City    4
dtype: int64

Non-NA values in each row:
 0    3
1    2
2    3
3    2
dtype: int64


In [ ]:
import pandas as pd
import numpy as np
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Score': [np.nan, 88, np.nan, 92],
    'Attempts': [1, 3, 2, 4]
}
df = pd.DataFrame(data)
rows_with_nan_score = df[pd.isna(df['Score'])]

print(rows_with_nan_score)

      Name  Score  Attempts
0    Alice    NaN         1
2  Charlie    NaN         2


In [ ]:
import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Score': [12, 18, 20, 15, 22]
}
df = pd.DataFrame(data)
rows_within_range = df[(df['Score'] >= 15) & (df['Score'] <= 20)]

print(rows_within_range)


      Name  Score
1      Bob     18
2  Charlie     20
3    David     15


In [ ]:
import pandas as pd
import numpy as np
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
df = pd.DataFrame(exam_data)
total_attempts = df['attempts'].sum()

print("Total examination attempts by the students:", total_attempts)

Total examination attempts by the students: 19


In [ ]:
import pandas as pd
data = {
    'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'John Doe', 'Jane Smith'],
    'Salary': [50000, 60000, 55000, 50000, 60000],
    'Designation': ['Developer', 'Manager', 'Tester', 'Developer', 'Manager']
}
df = pd.DataFrame(data)
print("DataFrame before removing duplicates:")
print(df)
df_unique = df.drop_duplicates()
print("\nDataFrame after removing duplicates:")
print(df_unique)

DataFrame before removing duplicates:
            Name  Salary Designation
0       John Doe   50000   Developer
1     Jane Smith   60000     Manager
2  Alice Johnson   55000      Tester
3       John Doe   50000   Developer
4     Jane Smith   60000     Manager

DataFrame after removing duplicates:
            Name  Salary Designation
0       John Doe   50000   Developer
1     Jane Smith   60000     Manager
2  Alice Johnson   55000      Tester


In [ ]:
import pandas as pd
employee_data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob'],
    'Salary': [50000, 60000, 70000, 50000, 60000],
    'Designation': ['Engineer', 'Manager', 'Analyst', 'Engineer', 'Manager']
}
df = pd.DataFrame(employee_data)

print("Original DataFrame:")
print(df)
df_no_duplicates = df.drop_duplicates()

print("\nDataFrame after removing duplicates:")
print(df_no_duplicates)

Original DataFrame:
      Name  Salary Designation
0    Alice   50000    Engineer
1      Bob   60000     Manager
2  Charlie   70000     Analyst
3    Alice   50000    Engineer
4      Bob   60000     Manager

DataFrame after removing duplicates:
      Name  Salary Designation
0    Alice   50000    Engineer
1      Bob   60000     Manager
2  Charlie   70000     Analyst


In [ ]:
import pandas as pd
# Sample data: 10 students, marks in 5 subjects
data = {
    'Student': ['Student1', 'Student2', 'Student3', 'Student4', 'Student5',
                'Student6', 'Student7', 'Student8', 'Student9', 'Student10'],
    'Math': [78, 85, 60, 90, 55, 65, 85, 88, 92, 40],
    'Science': [88, 92, 61, 65, 59, 77, 90, 82, 95, 30],
    'English': [68, 75, 65, 70, 60, 80, 78, 85, 80, 45],
    'History': [70, 80, 67, 75, 65, 70, 88, 90, 85, 35],
    'Geography': [92, 88, 72, 80, 70, 75, 91, 88, 90, 50]
}
# Create DataFrame
df = pd.DataFrame(data)
# Calculate percentage
try:
    df['Percentage'] = df.iloc[:, 1:].sum(axis=1) / 5
except ZeroDivisionError:
    print("Error: Division by zero encountered.")
except Exception as e:
    print(f"An error occurred: {e}")
def determine_grade(percentage):
    if percentage < 60:
        return 'Fail'
    elif percentage <= 80:
        return 'Grade B'
    else:
        return 'Grade A'

df['Grade'] = df['Percentage'].apply(determine_grade)
print(df)


     Student  Math  Science  English  History  Geography  Percentage    Grade
0   Student1    78       88       68       70         92        79.2  Grade B
1   Student2    85       92       75       80         88        84.0  Grade A
2   Student3    60       61       65       67         72        65.0  Grade B
3   Student4    90       65       70       75         80        76.0  Grade B
4   Student5    55       59       60       65         70        61.8  Grade B
5   Student6    65       77       80       70         75        73.4  Grade B
6   Student7    85       90       78       88         91        86.4  Grade A
7   Student8    88       82       85       90         88        86.6  Grade A
8   Student9    92       95       80       85         90        88.4  Grade A
9  Student10    40       30       45       35         50        40.0     Fail


In [ ]:
a = np.array([2, 4, 6])
b = a[0:2]
print(b)


[2 4]


In [ ]:
a = np.array([2, 4, 6, 8])
print(a)
b = a[1:]
print(b)


[2 4 6 8]
[4 6 8]


In [ ]:
a = np.array([2, 4, 6, 8])
print(a)
b = a[:3]
print(b)



[2 4 6 8]
[2 4 6]


In [ ]:
a = np.array([2, 4, 6, 8])
b = a[0:4]
print(b)
c = a[:4]
print(c)
d = a[0:]
print(d)
e = a[:]
print(e)


[2 4 6 8]
[2 4 6 8]
[2 4 6 8]
[2 4 6 8]


In [ ]:
a = np.array([[2, 4, 6, 8], [10, 20, 30, 40]])
print(a)
b = a[0:2, 0:3]
print(b)


[[ 2  4  6  8]
 [10 20 30 40]]
[[ 2  4  6]
 [10 20 30]]


In [ ]:
a = np.array([[2, 4, 6, 8], [10, 20, 30, 40]])
b = a[:,:]  #[all rows, all columns]
print(b)



[[ 2  4  6  8]
 [10 20 30 40]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])


[5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])


[1 3 5 7]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)



[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.arange(10)
arr.reshape(2, -1)



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
